# Generated by Django 5.2.9 on 2025-12-03 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScaffoldComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Tube', 'Tube'), ('Board', 'Board'), ('Coupler', 'Coupler'), ('Jack', 'Jack'), ('Frame', 'Frame'), ('Other', 'Other')], max_length=100)),
                ('length_mm', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('condition', models.CharField(choices=[('NEW', 'NEW'), ('GOOD', 'GOOD'), ('REPAIR', 'REPAIR'), ('SCRAP', 'SCRAP')], default='GOOD', max_length=10)),
                ('site', models.CharField(choices=[('Secunda', 'Secunda'), ('Sasolburg', 'Sasolburg')], max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('last_inspection', models.DateField(default=django.utils.timezone.now)),
                ('next_inspection', models.DateField()),
                ('is_in_use', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['condition', 'name'],
                'unique_together': {('asset_code', 'site')},
            },
        ),
    ]
